### ISSUE TITLE
any reason not to use partisan?

### ISSUE THREAD

**Issue by benoitc** [vitorenesduarte/ldb#59]
I was wondering why you were not using partisan for the peer service. Any reason for it?

**Comment by benoitc** [comment]
closing after our yesterday discussion.

**Comment by cmeiklejohn** [comment]
Where was the discussion?

**Comment by vitorenesduarte** [comment]
Twitter messages; here's the summary:
I've implemented this simple peer service for another project and ended up porting it to `ldb`.
Using partisan was not an option since we wanted to have total control on what we were doing and be able to change/break things as needed.
